name: SonarQube Analysis
on:
  push:
    branches:
      - master
steps:
  - name: Checkout code
    uses: actions/checkout@v2

  - name: Set up JDK 17
    uses: actions/setup-java@v2
    with:
      java-version: '17'

  - name: Build and test
    run: ./gradlew test

  - name: SonarQube Scan
    uses: sonarsource/sonarqube-scan-action@v1
    with:
      sonar-host-url: http://localhost:9000
      sonar-login: sqb_01943ac3aac35558f7605e42f1f198b3c9d068d9
